kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: elk
apiVersion: v1
data:
  fluent.conf: |-
    # <source>
    #   @type dummy
    #   dummy {"hello":"world"}
    #   auto_increment_key test
    #   tag dummy
    # </source>

    <source>
      @type syslog
      port 5140
      bind 0.0.0.0
      protocol_type tcp
      tag rsyslog
    </source>

    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match dummy>
      @type kafka_buffered

      # list of seed brokers
      brokers bootstrap.kafka.svc.cluster.local:9092

      # buffer settings
      buffer_type file
      buffer_path /var/log/fluent/dummy.*.buffer
      flush_interval 3s

      # topic settings
      default_topic dummy

      # data type settings
      output_data_type json
      compression_codec gzip

      # producer settings
      max_send_retries 1
      required_acks -1
      max_send_limit_bytes 100000
    </match>

    <match rsyslog.**>
      @type kafka_buffered

      # list of seed brokers
      brokers bootstrap.kafka.svc.cluster.local:9092

      # buffer settings
      buffer_type file
      buffer_path /var/log/fluent/rsyslog.*.buffer
      flush_interval 3s

      # topic settings
      default_topic rsyslog

      # data type settings
      output_data_type json
      compression_codec gzip

      # producer settings
      max_send_retries 1
      required_acks -1
      max_send_limit_bytes 100000
    </match>

    <match **>
      @type stdout
    </match>
