kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: elk
apiVersion: v1
data:
  fluent.conf: |-
    # <source>
    #   @type dummy
    #   dummy {"hello":"world"}
    #   auto_increment_key test
    #   tag dummy
    # </source>
    <source>
      @type twitter
      consumer_key        YOUR_CONSUMER_KEY        # Required
      consumer_secret     YOUR_CONSUMER_SECRET     # Required
      access_token        YOUR_ACCESS_TOKEN        # Required
      access_token_secret YOUR_ACCESS_TOKEN_SECRET # Required
      tag                 input.twitter.sampling   # Required
      timeline            tracking                 # Required (tracking or sampling or location or userstream)
      keyword             'Ruby,Python,#fleuntd'   # Optional (keyword has priority than follow_ids)
      follow_ids          14252,53235              # Optional (integers, not screen names)
      locations           31.110283, 129.431631, 45.619283, 145.510175  # Optional (bounding boxes; first pair specifies longitude/latitude of southwest corner)
      lang                ja,en                    # Optional
      output_format       nest                     # Optional (nest or flat or simple[default])
      flatten_separator   _                        # Optional
    </source>

    <source>
      @type syslog
      port 5140
      bind 0.0.0.0
      protocol_type tcp
      tag rsyslog
    </source>

    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <match input.twitter.sampling>
      @type kafka_buffered

      # list of seed brokers
      brokers bootstrap.kafka.svc.cluster.local:9092

      # buffer settings
      buffer_type file
      buffer_path /var/log/fluent/twitter.*.buffer
      flush_interval 3s

      # topic settings
      default_topic twitter

      # data type settings
      output_data_type json
      compression_codec gzip

      # producer settings
      max_send_retries 1
      required_acks -1
      max_send_limit_bytes 100000
    </match>

    <match dummy>
      @type kafka_buffered

      # list of seed brokers
      brokers bootstrap.kafka.svc.cluster.local:9092

      # buffer settings
      buffer_type file
      buffer_path /var/log/fluent/dummy.*.buffer
      flush_interval 3s

      # topic settings
      default_topic dummy

      # data type settings
      output_data_type json
      compression_codec gzip

      # producer settings
      max_send_retries 1
      required_acks -1
      max_send_limit_bytes 100000
    </match>

    <match rsyslog.**>
      @type kafka_buffered

      # list of seed brokers
      brokers bootstrap.kafka.svc.cluster.local:9092

      # buffer settings
      buffer_type file
      buffer_path /var/log/fluent/rsyslog.*.buffer
      flush_interval 3s

      # topic settings
      default_topic rsyslog

      # data type settings
      output_data_type json
      compression_codec gzip

      # producer settings
      max_send_retries 1
      required_acks -1
      max_send_limit_bytes 100000
    </match>

    <match **>
      @type stdout
    </match>
