apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: elk
spec:
  ports:
  - port: 24224
    name: forward
  - port: 5140
    name: syslog
  clusterIP: None
  selector:
    app: fluentd
