apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fluentd
  namespace: elk
spec:
  selector:
    matchLabels:
      app: fluentd
  serviceName: "fluentd"
  replicas: 1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: fluentd
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.2-debian-kafka
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 24224
          name: forward
        - containerPort: 5140
          name: syslog
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu:    100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /fluentd/etc
          # mountPath: /fluentd/etc/fluentd.yml
          # subPath: fluentd.yml
        - name: log
          mountPath: /var/log
      volumes:
      - name: config
        configMap:
          name: fluentd-config
      - name: log
        hostPath:
          path: /tmp/var/log
