apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  namespace: elk
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var"
