kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: log-pv-claim
  namespace: elk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
