# https://www.elastic.co/guide/en/filebeat/reference/current/docker.html
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      # securityContext:
      #   runAsUser: 1000
      #   fsGroup: 1000
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.2
        # args: ["-c", "/etc/filebeat/filebeat.yml", "-e"]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu:    100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: var
          mountPath: /var
        # - name: log
        #   mountPath: /var/log
        # - name: docker-log
        #   mountPath: /var/lib/docker
        # - name: docker-sock
        #   mountPath: /var/run/docker.sock
        # - name: docker-log
        #   mountPath: /var/lib/docker
        # - name: log
        #   mountPath: /var/log
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      # - name: init-config
      #   configMap:
      #     name: init-config
      # - name: docker-sock
      #   hostPath:
      #     path: /var/run/docker.sock
      # - name: docker-log
      #   hostPath:
      #     path: /var/lib/docker
      # - name: log
      #   hostPath:
      #     path: /var/log
      # - name: log
      #   hostPath:
      #     path: /tmp/var/log
      # - name: docker-log
      #   hostPath:
      #     path: /tmp/var/lib/docker
      - name: var
        hostPath:
          path: /var
      #     type: DirectoryOrCreate
