# https://www.elastic.co/guide/en/filebeat/reference/current/docker.html
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    matchLabels:
      app: filebeat
  replicas: 1
  template:
    metadata:
      labels:
        app: filebeat
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu:    100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat
      volumes:
      - name: config
        configMap:
          name: filebeat-config
