apiVersion: v1
data:
  MYSQL_HOST: <base64Host> # e.g run command: echo '127.0.0.1' | base64
  MYSQL_PASSWORD: <base64Password> # e.g run command: echo 'some-pass' | base64
  MYSQL_PORT: <base64Port> # Ensure its actually a number, use www.base64encode.org for this
  MYSQL_USER: <base64Username> # e.g run command: echo 'some-username' | base64
kind: Secret
metadata:
  name: ampath-elk-secrets
  namespace: elk
type: Opaque