apiVersion: v1
kind: Service
metadata:
  name: es-load-balancer
  namespace: elk
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: elasticsearch
  selector:
    app: elasticsearch
