apiVersion: v1
kind: Service
metadata:
  name: kibana-load-balancer
  namespace: elk
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      name: kibana
  selector:
    app: kibana