apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pipeline-pv
  namespace: elk
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/docker/logstash/pipeline"
