kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logstash-pipeline-pv-claim
  namespace: elk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
