# https://www.elastic.co/guide/en/logstash/reference/current/docker.html
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    matchLabels:
      app: logstash
  serviceName: "logstash"
  replicas: 1
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: logstash
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        role: es-master
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.0.0
        imagePullPolicy: Always
        env:
          - name: LS_JAVA_OPTS
            value: -Xmx8g -Xms1g
          - name: MYSQL_HOST
            valueFrom:
                secretKeyRef:
                  name: ampath-elk-secrets
                  key: MYSQL_HOST
          - name: MYSQL_PORT
            valueFrom:
                secretKeyRef:
                  name: ampath-elk-secrets
                  key: MYSQL_PORT
          - name: MYSQL_USER
            valueFrom:
                secretKeyRef:
                  name: ampath-elk-secrets
                  key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: ampath-elk-secrets
                  key: MYSQL_PASSWORD
        ports:
        - containerPort: 9600
          name: monitoring
        - containerPort: 5044
          name: logstash
        - containerPort: 514
          name: rsyslog
        resources:
          limits:
            cpu:    6.0
            memory: 12Gi
          requests:
            cpu:    0.5
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline
        - name: logstash-lastrun-data
          mountPath: /tmp/last_run
        - name: jdbc-driver
          mountPath: /usr/share/logstash/jdbc_driver
      volumes:
      - name: config
        configMap:
          name: logstash-config
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline
  volumeClaimTemplates:
  - metadata:
      name: logstash-lastrun-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nfs-client
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: jdbc-driver
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-client"
      resources:
        requests:
          storage: 2Gi